use std::collections::HashSet;

use serde::{Deserialize, Serialize};

use crate::key::LogicalKey;

pub const CURRENT_SCHEMA_VERSION: u32 = 4;
/// Identifier given to the single preset every pre-v4 file migrates to, and to
/// the preset a fresh installation starts from.
pub const DEFAULT_PRESET_ID: &str = "default";
pub const DEFAULT_PRESET_NAME: &str = "Default";
pub const MAX_PRESET_NAME_LENGTH: usize = 60;
const MAX_COOLDOWN_MS: u32 = 60_000;
const MIN_INTERVAL_MS: u32 = 40;
const MAX_TIMER_INTERVAL_MS: u32 = 60_000;
const MAX_NATURAL_INTERVAL_MS: u32 = 5_000;
const MAX_PAUSE_CHANCE_PERCENT: u8 = 25;

/// A named, independently switchable set of run settings. The global shortcut
/// is deliberately not part of one: switching presets must never change how a
/// run is started or stopped.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Preset {
    /// Opaque, generated by the frontend. Identity lives here, not in the name,
    /// so two presets may share a name.
    pub id: String,
    pub name: String,
    pub keys: Vec<KeyEntry>,
    pub mode: Mode,
    pub timer: TimerConfig,
    pub natural: NaturalConfig,
    pub stop_after: Option<u32>,
    /// Optional application the run is restricted to. `None` keeps the run
    /// unrestricted, which is the behaviour every schema-v1 file migrates to.
    pub target_app: Option<TargetApp>,
}

impl Default for Preset {
    fn default() -> Self {
        Self {
            id: DEFAULT_PRESET_ID.to_owned(),
            name: DEFAULT_PRESET_NAME.to_owned(),
            keys: Vec::new(),
            mode: Mode::Timer,
            timer: TimerConfig { interval_ms: 100 },
            natural: NaturalConfig {
                naturalness: 50,
                advanced: None,
            },
            stop_after: None,
            target_app: None,
        }
    }
}

impl Preset {
    /// Field paths are relative to the preset. `AppConfig::validate` prefixes
    /// them with `presets[index].` so an error names the preset it belongs to.
    pub fn validate(&self) -> Vec<ValidationError> {
        let mut errors = Vec::new();

        if self.name.trim().is_empty() {
            errors.push(ValidationError::new("name", "required"));
        }
        if self.name.trim().chars().count() > MAX_PRESET_NAME_LENGTH {
            errors.push(ValidationError::new("name", "range"));
        }

        let mut seen = HashSet::new();
        for entry in &self.keys {
            if !seen.insert(entry.key) {
                errors.push(ValidationError::new("keys", "duplicate"));
                break;
            }
        }

        for (index, entry) in self.keys.iter().enumerate() {
            if !(1..=10).contains(&entry.weight) {
                errors.push(ValidationError::new(
                    format!("keys[{index}].weight"),
                    "range",
                ));
            }
            if entry.cooldown_ms > MAX_COOLDOWN_MS {
                errors.push(ValidationError::new(
                    format!("keys[{index}].cooldownMs"),
                    "range",
                ));
            }
        }

        if !(MIN_INTERVAL_MS..=MAX_TIMER_INTERVAL_MS).contains(&self.timer.interval_ms) {
            errors.push(ValidationError::new("timer.intervalMs", "range"));
        }

        if self.natural.naturalness > 100 {
            errors.push(ValidationError::new("natural.naturalness", "range"));
        }

        if let Some(advanced) = &self.natural.advanced {
            if !(MIN_INTERVAL_MS..=MAX_NATURAL_INTERVAL_MS).contains(&advanced.min_interval_ms) {
                errors.push(ValidationError::new(
                    "natural.advanced.minIntervalMs",
                    "range",
                ));
            }
            if !(MIN_INTERVAL_MS..=MAX_NATURAL_INTERVAL_MS).contains(&advanced.max_interval_ms) {
                errors.push(ValidationError::new(
                    "natural.advanced.maxIntervalMs",
                    "range",
                ));
            }
            if advanced.min_interval_ms > advanced.max_interval_ms {
                errors.push(ValidationError::new("natural.advanced", "ordering"));
            }
            if advanced.burst_intensity > 100 {
                errors.push(ValidationError::new(
                    "natural.advanced.burstIntensity",
                    "range",
                ));
            }
            if advanced.pause_chance_percent > MAX_PAUSE_CHANCE_PERCENT {
                errors.push(ValidationError::new(
                    "natural.advanced.pauseChancePercent",
                    "range",
                ));
            }
        }

        if self
            .stop_after
            .is_some_and(|seconds| !(1..=86_400).contains(&seconds))
        {
            errors.push(ValidationError::new("stopAfter", "range"));
        }

        if self
            .target_app
            .as_ref()
            .is_some_and(|target| target.id.trim().is_empty())
        {
            errors.push(ValidationError::new("targetApp.id", "required"));
        }

        errors
    }

    /// Adds the start-only requirement that at least one key has been selected.
    pub fn validate_for_start(&self) -> Vec<ValidationError> {
        let mut errors = self.validate();
        if self.keys.is_empty() {
            errors.push(ValidationError::new("keys", "required"));
        }
        errors
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AppConfig {
    pub schema_version: u32,
    /// App-level, never per-preset: switching presets must not change how a run
    /// is started and stopped.
    pub global_shortcut: String,
    pub active_preset_id: String,
    pub presets: Vec<Preset>,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            global_shortcut: "CommandOrControl+Shift+K".to_owned(),
            active_preset_id: DEFAULT_PRESET_ID.to_owned(),
            presets: vec![Preset::default()],
        }
    }
}

impl AppConfig {
    pub fn active_preset(&self) -> Option<&Preset> {
        self.presets
            .iter()
            .find(|preset| preset.id == self.active_preset_id)
    }

    fn active_preset_index(&self) -> Option<usize> {
        self.presets
            .iter()
            .position(|preset| preset.id == self.active_preset_id)
    }

    /// Validates values that may be stored in the durable configuration file.
    pub fn validate(&self) -> Vec<ValidationError> {
        let mut errors = Vec::new();

        if self.schema_version != CURRENT_SCHEMA_VERSION {
            errors.push(ValidationError::new("schemaVersion", "unsupported-schema"));
        }

        if self.presets.is_empty() {
            errors.push(ValidationError::new("presets", "required"));
        }

        let mut seen = HashSet::new();
        for preset in &self.presets {
            if !seen.insert(preset.id.as_str()) {
                errors.push(ValidationError::new("presets", "duplicate"));
                break;
            }
        }

        for (index, preset) in self.presets.iter().enumerate() {
            if preset.id.trim().is_empty() {
                errors.push(ValidationError::new(
                    format!("presets[{index}].id"),
                    "required",
                ));
            }
            errors.extend(preset.validate().into_iter().map(|error| {
                ValidationError::new(format!("presets[{index}].{}", error.field), error.code)
            }));
        }

        if self.active_preset_index().is_none() {
            errors.push(ValidationError::new("activePresetId", "unknown"));
        }

        errors
    }

    /// Adds the start-only requirement that the active preset has a key.
    pub fn validate_for_start(&self) -> Vec<ValidationError> {
        let mut errors = self.validate();
        if let Some(index) = self.active_preset_index() {
            if self.presets[index].keys.is_empty() {
                errors.push(ValidationError::new(
                    format!("presets[{index}].keys"),
                    "required",
                ));
            }
        }
        errors
    }
}

/// A user-visible application, identified by the stable platform identifier
/// (bundle identifier on macOS, executable name on Windows) and shown by name.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TargetApp {
    pub id: String,
    pub name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct KeyEntry {
    pub key: LogicalKey,
    pub weight: u8,
    /// Natural mode only. Milliseconds this key stays unselectable after it is
    /// pressed. `0` disables the cooldown, which is what every pre-v3 file
    /// migrates to.
    pub cooldown_ms: u32,
}

impl KeyEntry {
    pub const fn new(key: LogicalKey) -> Self {
        Self {
            key,
            weight: 1,
            cooldown_ms: 0,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Mode {
    Timer,
    Natural,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct TimerConfig {
    pub interval_ms: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NaturalConfig {
    pub naturalness: u8,
    pub advanced: Option<NaturalOverrides>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct NaturalOverrides {
    pub min_interval_ms: u32,
    pub max_interval_ms: u32,
    pub burst_intensity: u8,
    pub pause_chance_percent: u8,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationError {
    pub field: String,
    pub code: String,
}

impl ValidationError {
    pub fn new(field: impl Into<String>, code: impl Into<String>) -> Self {
        Self {
            field: field.into(),
            code: code.into(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn preset(id: &str) -> Preset {
        Preset {
            id: id.to_owned(),
            name: format!("Preset {id}"),
            ..Preset::default()
        }
    }

    fn config_with(presets: Vec<Preset>) -> AppConfig {
        AppConfig {
            active_preset_id: presets[0].id.clone(),
            presets,
            ..AppConfig::default()
        }
    }

    #[test]
    fn config_validation_reports_each_invalid_field() {
        let invalid = Preset {
            keys: vec![
                KeyEntry {
                    key: LogicalKey::KeyA,
                    weight: 0,
                    cooldown_ms: 0,
                },
                KeyEntry::new(LogicalKey::KeyA),
            ],
            timer: TimerConfig { interval_ms: 39 },
            natural: NaturalConfig {
                naturalness: 101,
                advanced: Some(NaturalOverrides {
                    min_interval_ms: 5_001,
                    max_interval_ms: 39,
                    burst_intensity: 101,
                    pause_chance_percent: 101,
                }),
            },
            stop_after: Some(0),
            ..preset("second")
        };
        // The invalid preset sits at index 1 so a hard-coded `presets[0].`
        // prefix cannot pass this test.
        let config = config_with(vec![preset("first"), invalid]);

        let errors = config.validate();
        for (field, code) in [
            ("presets[1].keys", "duplicate"),
            ("presets[1].keys[0].weight", "range"),
            ("presets[1].timer.intervalMs", "range"),
            ("presets[1].natural.naturalness", "range"),
            ("presets[1].natural.advanced", "ordering"),
            ("presets[1].natural.advanced.minIntervalMs", "range"),
            ("presets[1].natural.advanced.maxIntervalMs", "range"),
            ("presets[1].natural.advanced.burstIntensity", "range"),
            ("presets[1].natural.advanced.pauseChancePercent", "range"),
            ("presets[1].stopAfter", "range"),
        ] {
            assert!(
                errors
                    .iter()
                    .any(|error| error.field == field && error.code == code),
                "missing {field}/{code} in {errors:?}"
            );
        }
        assert!(
            !errors
                .iter()
                .any(|error| error.field.starts_with("presets[0]"))
        );
    }

    #[test]
    fn config_validation_requires_a_key_in_the_active_preset_only_when_starting() {
        let config = config_with(vec![preset("first"), preset("second")]);
        assert!(config.validate().is_empty());
        assert!(
            config
                .validate_for_start()
                .iter()
                .any(|error| error.field == "presets[0].keys" && error.code == "required")
        );

        let active_second = AppConfig {
            active_preset_id: "second".to_owned(),
            ..config
        };
        assert!(
            active_second
                .validate_for_start()
                .iter()
                .any(|error| error.field == "presets[1].keys" && error.code == "required")
        );
    }

    #[test]
    fn config_validation_bounds_the_per_key_cooldown() {
        let config_with_cooldown = |cooldown_ms| {
            config_with(vec![Preset {
                keys: vec![KeyEntry {
                    key: LogicalKey::KeyA,
                    weight: 1,
                    cooldown_ms,
                }],
                ..preset("first")
            }])
        };

        assert!(config_with_cooldown(0).validate().is_empty());
        assert!(config_with_cooldown(60_000).validate().is_empty());
        assert!(
            config_with_cooldown(60_001)
                .validate()
                .iter()
                .any(
                    |error| error.field == "presets[0].keys[0].cooldownMs" && error.code == "range"
                )
        );
        assert_eq!(KeyEntry::new(LogicalKey::KeyA).cooldown_ms, 0);
    }

    #[test]
    fn config_validation_caps_pause_chance_at_twenty_five_percent() {
        let config_with_pause_chance = |pause_chance_percent| {
            config_with(vec![Preset {
                natural: NaturalConfig {
                    naturalness: 50,
                    advanced: Some(NaturalOverrides {
                        min_interval_ms: 100,
                        max_interval_ms: 500,
                        burst_intensity: 50,
                        pause_chance_percent,
                    }),
                },
                ..preset("first")
            }])
        };

        assert!(config_with_pause_chance(25).validate().is_empty());
        for pause_chance_percent in [26, 100] {
            assert!(
                config_with_pause_chance(pause_chance_percent)
                    .validate()
                    .iter()
                    .any(
                        |error| error.field == "presets[0].natural.advanced.pauseChancePercent"
                            && error.code == "range"
                    )
            );
        }
    }

    #[test]
    fn config_validation_bounds_the_preset_name() {
        let named = |name: &str| {
            config_with(vec![
                preset("first"),
                Preset {
                    name: name.to_owned(),
                    ..preset("second")
                },
            ])
        };

        assert!(named("A").validate().is_empty());
        assert!(
            named(&"n".repeat(MAX_PRESET_NAME_LENGTH))
                .validate()
                .is_empty()
        );
        // Trailing whitespace is trimmed away before the length is measured.
        assert!(
            named(&format!("{}   ", "n".repeat(MAX_PRESET_NAME_LENGTH)))
                .validate()
                .is_empty()
        );
        for empty in ["", "   ", "\t"] {
            assert!(
                named(empty)
                    .validate()
                    .iter()
                    .any(|error| error.field == "presets[1].name" && error.code == "required"),
                "{empty:?} was accepted"
            );
        }
        assert!(
            named(&"n".repeat(MAX_PRESET_NAME_LENGTH + 1))
                .validate()
                .iter()
                .any(|error| error.field == "presets[1].name" && error.code == "range")
        );
    }

    #[test]
    fn config_validation_requires_a_resolvable_active_preset() {
        let mut config = config_with(vec![preset("first"), preset("second")]);
        config.active_preset_id = "missing".to_owned();
        assert!(
            config
                .validate()
                .iter()
                .any(|error| error.field == "activePresetId" && error.code == "unknown")
        );
        assert_eq!(config.active_preset(), None);

        let empty = AppConfig {
            presets: Vec::new(),
            ..AppConfig::default()
        };
        assert!(
            empty
                .validate()
                .iter()
                .any(|error| error.field == "presets" && error.code == "required")
        );
    }

    #[test]
    fn config_validation_rejects_duplicate_and_empty_preset_ids() {
        let duplicated = config_with(vec![preset("same"), preset("same")]);
        assert!(
            duplicated
                .validate()
                .iter()
                .any(|error| error.field == "presets" && error.code == "duplicate")
        );

        let blank = config_with(vec![preset("first"), preset("  ")]);
        assert!(
            blank
                .validate()
                .iter()
                .any(|error| error.field == "presets[1].id" && error.code == "required")
        );
    }

    #[test]
    fn default_config_holds_exactly_one_active_preset() {
        let config = AppConfig::default();
        assert_eq!(config.presets.len(), 1);
        assert_eq!(config.active_preset(), Some(&Preset::default()));
        assert_eq!(config.presets[0].id, DEFAULT_PRESET_ID);
        assert_eq!(config.presets[0].name, DEFAULT_PRESET_NAME);
        assert!(config.validate().is_empty());
    }
}
